#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_w

if [ $AUTOCNF = yes ]
then
	# enable fusion of landing target velocity
	param set LTEST_MODE 1
	param set PLD_HACC_RAD 0.1
fi

# Start up Landing Target Estimator module
landing_target_estimator start
