# Rate of prediction step
dt_pred: 0.01
print_debug_msg: false

# Diagonal elements of the process covariance matrix Q, for constant acceleration model
# [x-x, y-y, z-z, vx-vx, vy-vy, vz-vz, ax-ax, ay-ay, az-az]
q_diag: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1 ,0.1 , 0.1, 0.1]

# Diagonal elements of the process covariance matrix Q, for constant velocity model
# # [x-x, y-y, z-z, vx-vx, vy-vy, vz-vz]
# q_diag: [5,5,5,10,10,10]

# Diagonal elements of the process covariance matrix Q, for constant velocity or acceleration models
r_diag: [0.01, 0.01, 0.01]

sigma_a: 1
sigma_p: 1
sigma_v: 1

# Provide estimate w.r.t this frame
tracking_frame: 'interceptor_odom'
# Topic name of the tag detections
apriltags_topic: '/tag_detections'
# Frame name of the detected target
target_frameid: 'tag'

# Get target measurements from TF tree
listen_tf: true

# Maximum uncertainty before rejecting a track [m^3] 
V_max: 100.0
# Minimum uncertainty for confirming a track [m^3]
V_certain: 30.0
# Minimum number of measurements to confirm a track
N_meas: 10
# Measurement association log-likelihood threshold
l_threshold: -100.0

# Maximum distance between  a state & measurement to consider them as a match (currently not used)
dist_threshold: 5.0

# False: Doesn't consider measurement track ID in measurement-state association 
use_track_id: false